version: '3.8'

services:
  backend:
    image: hemaspandanadhavuluri/justap-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://justtapEDLoans:justtapEDLoans@justap-edloans.x48q4c6.mongodb.net/?retryWrites=true&w=majority&appName=justap-edloans
      - PORT=5000
      - EMAIL_USER=justtapnagendra@gmail.com
      - EMAIL_PASS=lfxs gaqv ldyd rwnj
    networks:
      - app-network

  frontend:
    image: hemaspandanadhavuluri/justap-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge